$ServerIP = "134.209.147.41"
$User = "root"

Write-Host "Checking Java installation in container..."
ssh "$User@$ServerIP" "docker exec filepilot which java"
Write-Host "`nChecking Java version..."
ssh "$User@$ServerIP" "docker exec filepilot java -version 2>&1"
Write-Host "`nChecking installed Java packages..."
ssh "$User@$ServerIP" "docker exec filepilot dpkg -l | grep -i jre"
Write-Host "`nChecking JAVA_HOME..."
ssh "$User@$ServerIP" "docker exec filepilot printenv | grep JAVA"
